
INSERT INTO `grades` (`name`) VALUES
('non renseigné'),
('adjoint administratif 1ère classe'),
('adjoint administratif 2ème classe'),
('adjoint administratif 2ème classe non titulaire'),
('adjoint administratif principal de 1ère classe'),
('adjoint administratif principal de 2ème classe'),
('adjudant-chef'),
('adjudant'),
('agent de maîtrise'),
('agent de maîtrise principal'),
('adjoint technique de 1ère classe'),
('adjoint technique de 2ème classe'),
('adjoint technique de 2ème classe non titulaire'),
('attaché principal'),
('adjoint technique principal de 1ère classe'),
('adjoint technique principal de 2ème classe'),
('attaché'),
('caporal-chef'),
('commandant'),
('colonel'),
('contrôleur de travaux'),
('contrôleur de travaux en chef'),
('contrôleur principal de travaux'),
('caporal'),
('capitaine'),
('directeur territorial'),
('ingénieur en chef de classe exceptionnelle'),
('ingénieur en chef de classe normale'),
('ingénieur'),
('ingénieur principal'),
('Infirmier'),
('Infirmier Chef'),
('Infirmier d''encadrement'),
('Infirmier Principal'),
('jeune sapeur pompier 1'),
('jeune sapeur pompier 2'),
('jeune sapeur pompier 3'),
('jeune sapeur pompier 4'),
('jeune sapeur pompier breveté'),
('lieutenant-colonel'),
('lieutenant 1ère classe'),
('lieutenant 2ème classe'),
('major'),
('Médecin Commandant'),
('Médecin Colonel'),
('Médecin Capitaine'),
('Médecin Lieutenant Colonel'),
('rédacteur'),
('rédacteur chef'),
('rédacteur principal'),
('sapeur 1ère classe'),
('sapeur 2ème classe'),
('sergent-chef'),
('sergent'),
('technicien supérieur'),
('technicien supérieur chef'),
('technicien supérieur principal');


INSERT INTO `users` (`id`, `firstname`, `lastname`, `birthname`, `email`, `login`, `password`, `phone`, `cellphone`, `address`, `zipcode`, `city`, `birthday`, `birthplace`, `skype`, `is_active`, `permission_id`, `grade_id`, `role_id`, `created`, `modified`, `connected`) VALUES
(1, 'Florent', 'Maillard', '', 'florent.maillard.pro@gmail.fr', 'admin', '$2y$10$82fA2pFkODkaj6cbxD5S8Ob.KEzEE848qoAovzopb4stB8HAcLHVG', '0611214341', '', '', '', '', '1985-03-05', '', '', 1, NULL, 24, NULL, '2016-08-30', '2016-08-30', NULL),
(2, 'Nicolas', 'Hel', '', 'znirgal@gmail.com', 'nirgal', '$2y$10$IS67pIEg25UG6lN556WDleoEGpbAXBE2k7bYYtRt/4y7BaOI2SMua', '', '', '', '', '', NULL, '', '', 0, NULL, NULL, NULL, '2016-08-31', '2016-08-31', NULL),
(3, 'Gwenael', 'Prevot', '', 'prevotgwenael@gmail.com', 'frexwimsn', '$2y$10$zBLH6jfO99bjjNEif7qmquN0Ms2E7eE2we8BFrs2iODm7KKhxRbBi', '', '', '', '', '', NULL, '', '', 0, NULL, NULL, NULL, '2016-08-31', '2016-08-31', NULL),
(4, 'Olivier', 'Perrin', '', 'perrinolivier88@gmail.com', 'kaki88', '$2y$10$8Wn4cnW9eqsdrNfqPRbxM.YuOw/JUE4GbhYUHTyvskiIE1vIxtBta', '', '', '', '', '', NULL, '', '', 0, NULL, NULL, NULL, '2016-08-31', '2016-08-31', NULL);
